server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/braindeck
    username: braindeck
    password: braindeck
    driver-class-name: org.postgresql.Driver
  jpa:
#    hibernate:
#      ddl-auto: create
    properties:
      hibernate:
        default_schema: braindeck
    show-sql: true

  #  flyway:
#    url: jdbc:postgresql://localhost:5432/braindeck
#    user: braindeck
#    password: braindeck
#    baseline-on-migrate: true
#    installed-by: braindeck
#    schemas:
#      - public
#      - braindeck

  application:
    name: BrainDeckPSQL

  messages:
    basename: messages
    encoding: UTF-8

  web:
    locale: ru
    locale-resolver: fixed
logging:
  level:
    sql: info